-- AlterTable
ALTER TABLE "estatisticas" ALTER COLUMN "cartao" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "chutes" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "escanteios" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "posse_bola" SET DATA TYPE VARCHAR(30);
